spring.application.name=gateway-service
server.port=8080

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# Flight Service
spring.cloud.gateway.server.webflux.routes[1].id=flight-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/flights/**


# Booking Service
spring.cloud.gateway.server.webflux.routes[2].id=booking-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/bookings/**